import Timeline from "@/components/Timeline";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS Udemy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=l" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Timeline />
      </div>
    </>
  );
}
